<?php /** @var $this \MvcCore\Ext\Forms\View */ ?>
<?php /** @var $this->user \MvcCore\Ext\Auths\Basics\User */ ?>
<div class="mc-header relative">
	<?php echo $this->RenderBegin(); ?>
		<span class="user-info">
			<?php echo $this->Translate('User') ?>: <b><?php echo $this->user->FullName; ?></b>
		</span>
		<?php foreach ($this->form->GetFields() as $key => & $field): ?>
			<?php echo $field->Render(); ?>
		<?php endforeach; ?>
	<?php echo $this->RenderEnd(); ?>
</div>
