<?php /** @var $this \MvcCore\Ext\Form\Core\View */ ?>
<div class="mc-header absolute">
	<?php echo $this->RenderBegin(); ?>
		<button class="toggle button button-green"><span><b><?php echo $this->Translate('Sign In'); ?></b></span></button>
		<div class="content">
			<?php foreach ($this->form->GetFields() as $key => & $field): ?>
				<?php if ($key == 'username'): ?>
					<div class="text-inputs">
				<?php endif; ?>
				<?php echo $field->Render(); ?>
				<?php if ($key == 'password'): ?>
					</div>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>
	<?php echo $this->RenderEnd(); ?>
</div>