<?php
	/** @var $this \MvcCore\View */
	/** @var $controller \MvcCore\Controller */
	/** @var $this->authForm \MvcCore\Ext\Form|NULL */
	$controller = & $this->GetController();
?><!DOCTYPE HTML>
<html lang="<?php echo $this->lang; ?>-<?php echo $this->locale; ?>">
	<head>
		<meta charset="UTF-8" />
		<title><?php echo $this->document->Title; ?> | MvcCore</title>
		<base href="<?php echo $controller->GetRequest()->GetBaseUrl(); ?>/" />
		<link rel="shortcut icon" href="<?php echo $this->AssetUrl('/static/img/theme/favicon.ico'); ?>" />
		<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
		<?php if ($this->mediaSiteKey !== 'full'): ?>
			<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes" />
		<?php endif; ?>
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<script>var timestamp=+new Date;(function(a,b,c,d,e,f){if(b[c]('Opera'))b=b[d](e,f);if(b[c]('Trident/'))b=b[d](/ rv:([0-9\.]*)\)/g,e+'$1)');a.setAttribute('data-browser',b);a.className=f;})(document.documentElement,navigator.userAgent,'match','replace',' MSIE ','')</script>
		<meta property="og:image" content="<?php echo $this->document->OgImage; ?>"/>
		<meta property="og:site_name" content="<?php echo $this->ogSiteName; ?>" />
		<meta property="og:title" content="<?php echo $this->document->OgTitle; ?>" />
		<meta property="og:url" content="<?php echo $this->ogUrl; ?>" />
		<meta property="og:description" content="<?php echo $this->document->OgDescription; ?>" />
		<meta itemprop="name" content="<?php echo $this->document->ItempropName; ?>" />
		<meta itemprop="description" content="<?php echo $this->document->ItempropDescription; ?>" />
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

		  ga('create', '<?php echo $this->googleAnalyticsCode; ?>', 'auto');
		  ga('send', 'pageview');
		</script>
		<?php echo $this->Css('fixedHead')->Render(); ?>
		<?php echo $this->Css('fixedHeadPrint')->Render(); ?>
		<?php echo $this->Css('varHead')->Render(); ?>
		<?php echo $this->Js('fixedHead')->Render(); ?>
		<?php echo $this->Js('varHead')->Render(); ?>
		<meta name="author" content="Tom Flidr <tomflidr(at)gmail(dot)com>" />
	</head>
	<body>
		<input id="data-js-website-settings" type="hidden" value="<?php
			echo $this->jsonAttr((object) [
				'mediaSiteVersion'		=> $this->mediaSiteVersion,
			]);
		?>" />
		<!--[if lt IE 9]><div class="old-browser-warning"><p>Your browser is <b>very</b> old.<br />Please install any actual browser, <br />for example <a href="https://www.google.com/chrome" target="_blank">Google Chrome</a> or <a href="https://www.mozilla.org/en/firefox/new" target="_blank">Mozilla Firefox</a>.</p></div><![endif]-->
		<div class="master-container">
			<div class="mc-content">
				<?php if ($this->authForm) echo $this->authForm->Render(); ?>
				<div class="mc-content">
					<div class="document <?php
						echo $controller->GetParam('controller'), ' ',
							$controller->GetParam('action'), ' ',
							$this->authForm && isset($this->authForm->User) ? 'authenticated' : ''
					?>">
						<?php echo $this->GetContent(); ?>
					</div>
				</div>
				<?php echo $this->RenderLayout('./layout/footer.' . $this->mediaSiteVersion); ?>
			</div>
		</div>
	</body><?php 
	/* anything to say: Run(); */
	echo $this->Js('fixedFoot')->Render();
	echo $this->Js('varFoot')->Render();
?></html>
