<?php /** @var $this \MvcCore\View */ ?>
<h1><?php echo $this->Translate('Thanks'); ?></h1>
<p>
    <?php echo $this->Translate('Thank you for your answers, the questionnaire is evaluated anonymously.'); ?>
</p>
<p>
    <?php echo str_replace(
		array('%linkBegin%', '%linkEnd%'),
		array('<br /><a href="' . $this->Url('Statistics:Index', array('path' => $this->Path)) . '">', '</a>'),
		$this->Translate('If you are interested in how other people answered, %linkBegin%you can see the global anonymous results here%linkEnd%.')
	); ?>
</p>
<p>
    <a href="<?php echo $this->BackLink; ?>"><?php echo $this->Translate('Back to questions'); ?></a>
</p>
