<?php /** @var $this \MvcCore\View */ ?>
<h1><?php echo $this->Translate('Questionnaires'); ?></h1>
<?php if ($this->Questionnaires): ?>
	<p><?php echo $this->Translate('Please choose one of these questionnaires.'); ?></p>
	<div class="hr"></div>
	<?php foreach($this->Questionnaires as $questionnaire): ?>
		<div>
			<h3>
				<a href="<?php echo $questionnaire->GetUrl(); ?>">
					<?php echo $questionnaire->Title; ?>
				</a>
			</h3>
			<p>
				<?php echo $questionnaire->Perex; ?>
			</p>
		</div>
	<?php endforeach; ?>
<?php else: ?>
	<p><b>No XML questionnaires defined in path: '<?php echo $this->$Path; ?>'.</b></p>
<?php endif; ?>