<style type="text/css">
	#nette-debug-session-panel{max-width:800px;max-height:600px;overflow:auto;}
	#nette-debug-session-panel table{width:100%;margin-bottom:0.5em;}
	#nette-debug-session-panel .key{width:100px !important;font-weight:bolder;}
	#nette-debug-session-panel thead td{font-weight:bolder;font-size:14px;line-height:18px;vertical-align:middle;}
	#nette-debug-session-panel pre{max-width:600px !important;overflow: auto;padding:0;border:0px none !important;border-radius:0px !important;box-shadow:none !important;}
	#nette-debug-session-panel .h1,
	#nette-debug-session-panel h2{margin:0 !important;font-family:inherit !important;font-weight:bold !important;color:inherit !important;text-rendering:optimizelegibility !important;}
	#nette-debug-session-panel h2{font-size:24px !important;line-height:36px !important;}
	#nette-debug-session-panel strong{font-weight:bold !important;}
	#nette-debug-session-panel-title{font-size:30px !important;line-height:36px !important;overflow:hidden;}
	#nette-debug-session-panel-title img{vertical-align:middle;position:absolute;margin-top:10px;margin-left:5px;overflow:hidden;}
	#nette-debug-session-panel-title small{font-weight:normal;font-size:10px !important;}
	#nette-debug-session-panel-title .pull-left{display:block;float:left !important;}
	#nette-debug-session-panel-title .pull-left b{padding:0 20px 0 28px;}
	#nette-debug-session-panel-title .pull-right,
	#nette-debug-session-panel .pull-right{display:block;float:right !important;}
	#nette-debug-session-panel-title .clear,
	#nette-debug-session-panel .clear{clear:both !important;}
	#nette-debug-session-panel-title .expiration,
	#nette-debug-session-panel .expiration{font-weight:normal !important;font-size:80%;}
	#nette-debug-session-panel-title .expiration{margin-right:5px;font-size:70%;line-height:200%;vertical-align:middle;}
	#nette-debug-session-panel [title]{cursor:help;}
</style>
<div class"h1" id="nette-debug-session-panel-title">
	<span class="pull-left">
		<img width="16" height="16" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAMRJREFUeNpiZCAT2Orr6QOpAhYyNdcDqQAgdmAhw9YFQKwAxAaHL176yESirRegmh2Amh+CxFlIsNUAKpQA1HwRJs9EpK3Imjciq2Eh0lYQmADUvBBdLRMRtoLAAqDmQmyWERuIBlBXYQBmdIFHL18elJcQ3wBkWgCxBFQYRGcAxcHyxLjgAQ4xDHFGHAG4ARrfMI0N2AIQwwCgZnuoZgFCGjGiEag5Hhp1II0FhDSiGADU3A/NHAnEakSJd6jtZAGAAAMA89NIrMVVIPoAAAAASUVORK5CYII=" />
		<b>Session Panel</b>
	</span>
	<small class="pull-right expiration">
		<strong>Max.&nbsp;life&nbsp;time:</strong>&nbsp;<?php echo SessionPanel::FormateDate(SessionPanel::$SessionMaxTime); ?>
	</small>
	<span class="clear"></span>
</div>
<div id="nette-debug-session-panel">
	<?php foreach (SessionPanel::$Session as $sectionName => $section): ?>
		<?php $sessionMeta = SessionPanel::$SessionMetaStore[$sectionName]; ?>
		<table>
			<thead>
				<tr>
					<td colspan="2">
						<?php echo $sectionName; ?>
						<span class="pull-right expiration">
							<strong>Expiration after: </strong>
							<?php if ($sessionMeta->lifeType == 'time'): ?>
								<span title="Expiration after actual shown time."><?php
									echo $sessionMeta->timeFormated;
								?></span>
							<?php elseif ($sessionMeta->lifeType == 'browser'): ?>
								<span title="Expiration after browser close.">Browser has closed.</span>
							<?php else: ?>
								<span title="Expiration is not set.">No</span>
							<?php endif; ?>
						</span>
						<span class="clear"></span>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($section as $key => $typeAndDumpedValues):  ?>
					<tr>
						<td class="key">
							<?php echo $key; ?><br /><i>(<?php echo $typeAndDumpedValues[0]; ?>)</i>
						</td>
						<td>
							<?php echo DebugHelpers::clickableDump($typeAndDumpedValues[1]); ?>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	<?php endforeach; ?>
</div>