<?php
	/** @var $this \MvcCore\Ext\Forms\View */

	/** @var $controller \MvcCore\Controller */
	$controller = & $this->GetController();
	/** @var $form \MvcCore\Ext\Form */
	$form = & $this->GetForm();
	/** @var $fields \MvcCore\Ext\Forms\Field[] */
	$fields = & $form->GetFields();
	
	echo $this->RenderBegin();
	
	echo $this->RenderErrors();
?>
	<div class="fieldset fieldset-person">
		<?php if ($this->personsForm): ?> 
			<h2><?php echo $this->Translate('About you'); ?></h2>
		<?php else: ?>
			<h2><?php echo $this->Translate('Questions'); ?></h2>
		<?php endif; ?>
		<?php $previousKey = ''; ?>
		<?php foreach ($fields as $key => & $field): ?>
			<?php $fieldName = $field->GetName(); ?>
			<?php if ($fieldName == 'send' && $controller->GetView()->displayFacebookShare): ?>
				<?php echo $this->Facebook()->ShareButton('questionnaire-bottom'); ?>
			<?php endif; ?>
			<?php if (strpos($fieldName, 'question') === 0 && strpos($fields[$previousKey]->GetName(), 'person') === 0): ?>
					</div>
				<div class="hr"></div>
				<div class="fieldset fieldset-questions">
				<h2><?php echo $this->Translate('Questions'); ?></h2>
			<?php endif; ?>
			<div class="field <?php echo implode(' ', $field->GetCssClasses()); ?>">
				<?php echo $field->Render(); ?>
			</div>
			<?php $previousKey = $key; ?>
		<?php endforeach; ?>
		<div class="clear"></div>
	</div>

<?php echo $this->RenderEnd(); ?>
