<?php
	/** @var $this \MvcCore\Ext\Forms\View */

	/** @var $controller \MvcCore\Controller */
	$controller = & $this->GetController();
	/** @var $form \MvcCore\Ext\Form */
	$form = & $this->GetForm();
	/** @var $fields \MvcCore\Ext\Forms\Field[] */
	$fields = & $form->GetFields();
	
	echo $this->RenderBegin();
	
	echo $this->RenderErrors();
?>
	<div class="fieldset fieldset-person">
		<?php foreach ($fields as $key => & $field): ?>
			<div class="field <?php echo implode(' ', $field->GetCssClasses()); ?>">
				<?php echo $field->Render(); ?>
			</div>
			<?php if ($field->GetType() === 'submit'): ?>
				<div id="statistics-questions-loading" class="loading"><span><?php 
					echo $this->Translate('Loading statistics...');
				?></span></div>
			<?php endif; ?>
		<?php endforeach; ?>
	</div>

<?php echo $this->RenderEnd(); ?>
