<?php 
	$newParams = array_merge(array(), $this->Request->params);
	unset($newParams['controller'], $newParams['action']);
	$navigationItems = array(
		'full'		=> 'klasicky',
		'mobile'	=> 'pro mobily',
	);
?>
<div class="mc-footer-media-navigation">
	Zobrazit: <?php
	$i = 0;
	foreach ($navigationItems as $key => $value):
		if ($key == $this->MediaSiteKey):
			?><span><?php
			echo $value;
			?></span><?php
		else:
			?><a <?php
			if ($key == $this->MediaSiteKey) echo ' class="selected"';
				 ?>href="<?php
			echo $this->Url(
				'self', 
				array_merge($newParams, array(
					'mediaSiteKey'		=> $key, 
					'media_site_key'	=> $key,
				))
			);
				?>"><?php
			echo $value;
			?></a><?php
		endif;
		if (++$i > 0 && $i < count($navigationItems)) echo ', ';
	endforeach;
?></div>