<?php
	/** @var $this->request \MvcCore\Request */ 
	$navigationItems = [
		\MvcCore\Ext\Routers\IMedia::MEDIA_VERSION_FULL	=> $this->Translate('classic'),
		\MvcCore\Ext\Routers\IMedia::MEDIA_VERSION_MOBILE	=> $this->Translate('mobile'),
	];
	$fullUrl = $this->request->GetFullUrl();
	$questionMarchMatched = mb_strpos($fullUrl, '?') !== FALSE;
	$i = 0;
?><div class="mc-footer-media-navigation"><?php
	echo $this->Translate('Display') . ': ';
	foreach ($navigationItems as $key => $value):
		if ($key == $this->mediaSiteVersion):
			?><span><?php echo $value; ?></span><?php
		else:
			?><a href="<?php
			/*echo $this->Url(
				'self',
				[\MvcCore\Ext\Routers\IMedia::SWITCH_MEDIA_VERSION_URL_PARAM  => $key]
			);*/
			echo $fullUrl 
				. ($questionMarchMatched ? '&' : '?')
				. \MvcCore\Ext\Routers\IMedia::SWITCH_MEDIA_VERSION_URL_PARAM 
				. '=' . $key;
			?>"><?php echo $value; ?></a><?php
		endif;
		if (++$i > 0 && $i < count($navigationItems)) echo ', ';
	endforeach;
?></div>
