<?php /** @var $this \MvcCore\View */ ?>
<div class="mc-footer-media-navigation"><?php
	$newParams = array_merge(array(), $this->Request->Params);
	unset($newParams['controller'], $newParams['action']);
	$navigationItems = array(
		\MvcCore\Ext\Router\MediaSiteKey::FULL		=> $this->Translate('classic'),
		\MvcCore\Ext\Router\MediaSiteKey::MOBILE	=> $this->Translate('mobile'),
	);
	echo $this->Translate('Display') . ': ';
	$i = 0;
	foreach ($navigationItems as $key => $value):
		if ($key == $this->MediaSiteKey):
			?><span><?php
				echo $value;
			?></span><?php
		else:
			?><a <?php
				if ($key == $this->MediaSiteKey) echo ' class="selected"';
			?>href="<?php
				echo $this->Url(
					'self', 
					array_merge($newParams, array(
						\MvcCore\Ext\Router\Media::MEDIA_SITE_KEY_URL_PARAM			=> $key, 
						\MvcCore\Ext\Router\Media::MEDIA_SITE_KEY_SWITCH_URL_PARAM	=> $key,
					))
				);
			?>"><?php
				echo $value;
			?></a><?php
		endif;
		if (++$i > 0 && $i < count($navigationItems)) echo ', ';
	endforeach;
?></div>